[[GEOS]]
arch = "aarch64"
git-tree-sha1 = "c47f9947d774c2f9b6b21b8d664eddd9bd153117"
os = "macos"

    [[GEOS.download]]
    sha256 = "1fc6921e4624cc3af2cf60ae4406018756ef437601213266218daa4575808811"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.aarch64-apple-darwin.tar.gz"
[[GEOS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e387328e0199b147da6cfab3c737eb998cbe340"
libc = "glibc"
os = "linux"

    [[GEOS.download]]
    sha256 = "f7c13a4d589cc2e3648a6ab3d00ff07d5cd5d3442c1cf56c12e31761c8a6c2ba"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GEOS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f2d908dc3008ca9be41b76de7d25da31f1774e6"
libc = "musl"
os = "linux"

    [[GEOS.download]]
    sha256 = "cd3aeb7804b5ccad9459944af9dac26312a558b15be4cde87f7880b6aa006ec7"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.aarch64-linux-musl-cxx11.tar.gz"
[[GEOS]]
arch = "aarch64"
git-tree-sha1 = "2308f9da135f8a82dc75afdff0de60269d0904a1"
os = "freebsd"

    [[GEOS.download]]
    sha256 = "95f08d10c8d6c4ab98f3fdf2e9d2354e26dd88c96c419eddde19f980bdae90d9"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.aarch64-unknown-freebsd.tar.gz"
[[GEOS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0733cfc33bdc8c9019d62e302c48861597a36fd7"
libc = "glibc"
os = "linux"

    [[GEOS.download]]
    sha256 = "16ce5d2d0152ea1e84d8788ba95f2d33430520bd6f54c887bf3ad3a8c6ad73ea"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GEOS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fa8fa0be74048ae0b73b6c74bcb048608b708fa"
libc = "musl"
os = "linux"

    [[GEOS.download]]
    sha256 = "940bc3f9a5f8e5826424c5acd72a8f906091e7ce69f94a3a31e1520ddd39a572"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GEOS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7c6760ee61f17d0f3246c37e0f2b60c00e0eb5b"
libc = "glibc"
os = "linux"

    [[GEOS.download]]
    sha256 = "f6ad2c18100ceef343c47d0352d902eae4334ed1038bb38556b03dd655234998"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GEOS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30a41504136a7f1c0dbe3fdd4039e9a114034d08"
libc = "musl"
os = "linux"

    [[GEOS.download]]
    sha256 = "3781e4362a94055ba67eb12c037a969f098b21ebb99620553a8f44879eab7e27"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GEOS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a839f088cf3275f2d85fd471a3238f2cab72d57"
libc = "glibc"
os = "linux"

    [[GEOS.download]]
    sha256 = "a0e2c37bdb7954335afd8132a6dd05b7753874ac70cfd4cfbbf6f57b7e37c1e2"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.i686-linux-gnu-cxx11.tar.gz"
[[GEOS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cd0dcdc8e4b334ed3f00f321554ed8f7a5f3577"
libc = "musl"
os = "linux"

    [[GEOS.download]]
    sha256 = "bd3512340f004c4ac295ff09155f216e7972fbb5635b92a51c9d00cf0772a8e5"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.i686-linux-musl-cxx11.tar.gz"
[[GEOS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbe3450e4c02cace3b7d9fa7d74fad5b3cdc65da"
os = "windows"

    [[GEOS.download]]
    sha256 = "ee3c3aa5f3ade07c0e1fe5ef4feb6bf4ca3f8690a40b0b0d24b993776fb48145"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.i686-w64-mingw32-cxx11.tar.gz"
[[GEOS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5be5965d97599c939184ba61960f6718b8b397b"
libc = "glibc"
os = "linux"

    [[GEOS.download]]
    sha256 = "f5b28e412f841211482ff16f3d68120275bf6b396b3567ea7a307c2a63c3ef29"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GEOS]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "726843efe3f6d72fc64bfd71c52570a53ce52887"
libc = "glibc"
os = "linux"

    [[GEOS.download]]
    sha256 = "2344e0551073e9112f3754dd97be6a32c72780e90c86ea9b9d2e03afc0895ad4"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.riscv64-linux-gnu-cxx11.tar.gz"
[[GEOS]]
arch = "x86_64"
git-tree-sha1 = "9ba6f8988299173da9e4cb66908a99841b30e263"
os = "macos"

    [[GEOS.download]]
    sha256 = "c06561674462a78c7c3432ae1fb7c9283d11a55df5b558e9d3c90fa7220b7777"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.x86_64-apple-darwin.tar.gz"
[[GEOS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20674d5219295a25366a355e646011ba67c93e0e"
libc = "glibc"
os = "linux"

    [[GEOS.download]]
    sha256 = "92a7ac552c2c4bce68607786a82b836daa283c7fd251ff3b025ab1a43e4b1b0e"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GEOS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c59b61302d59063fc1891b2de6ed928978ee3188"
libc = "musl"
os = "linux"

    [[GEOS.download]]
    sha256 = "0d094fc6487b5767f5b81da7ade2024d53b8c14180b41ccac813a92586c03aee"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.x86_64-linux-musl-cxx11.tar.gz"
[[GEOS]]
arch = "x86_64"
git-tree-sha1 = "57b1b2ce5bbd04c21691e1b28861bcde30398fe7"
os = "freebsd"

    [[GEOS.download]]
    sha256 = "14d5e0e1c6369553fff43035e466bd19fe904fb72a661e7c90e26de600ad9e6b"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.x86_64-unknown-freebsd.tar.gz"
[[GEOS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ead1e05382d1935b96ffbe5de5feac25b9c1dc3a"
os = "windows"

    [[GEOS.download]]
    sha256 = "93186bfcdaa6d4a6ee045ad288cbb4db2302f88bb9c38ac1b12b4ccfdd74af85"
    url = "https://github.com/JuliaBinaryWrappers/GEOS_jll.jl/releases/download/GEOS-v3.14.1+0/GEOS.v3.14.1.x86_64-w64-mingw32-cxx11.tar.gz"
